// Product screens for the landing, rendered in the structure of the current platform
// (sidebar sections, dashboard tabs, contact card, call transcript, lead gen) but in English
// with fictional North American freight data. No real client names or numbers.

const UI_STYLE = `Render it as a crisp, pixel-perfect desktop web-app screenshot, flat and straight-on, with no browser chrome, no device frame, no perspective and no watermark. Product: "MagnaQore Logistic", an AI calling and sales system for North American freight companies. Dark theme: page background deep warm charcoal #141311; panels and cards #1d1b18 with hairline borders #2c2925 and 12px rounded corners; primary text warm off-white #ece8e1; secondary text muted warm grey #8f8a82; one accent, amber-gold #e9a23b, used for the active navigation marker, count badges, primary buttons, progress fills, active tabs and toggles; green #3fae7a only for positive statuses; lead ratings shown as small rounded chips reading A, B, C or D. Typography: a clean geometric sans-serif similar to Manrope, calm spacing, 13–15px interface text that is sharp, legible and spelled correctly. Left sidebar about 230px wide: a small muted label "MagnaQore" above the bold product name "Logistic AI" with a bell icon; navigation with thin line icons in this order: Dashboard (small amber count badge), Contacts, Dialer, Calls, Chats, Lead gen, Assistant, Settings, Help, System; at the bottom a user block "Alex Morgan" with the role "Sales ops" and a log-out icon. Whenever the Dashboard page is shown, it starts with the page title "Dashboard" and the subtitle "Welcome back, Alex. Here is what is happening in the system.", then the status card, then one tab row with exactly three tabs — "Summary", "Tasks" (with its count badge) and "Progress" — and no other tabs anywhere on the page. All people, companies, phone numbers and figures are fictional; phone numbers use the US 555 range. English only.`;

export const PRODUCT_IMAGES = [
  {
    name: 'product-dashboard',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: Dashboard, with "Dashboard" highlighted in the sidebar. Page title "Dashboard" and subtitle "Welcome back, Alex. Here is what is happening in the system." A wide status card with a green dot and the label "Working hours", the line "Calls run 8:00 AM–5:00 PM in each lead's local time zone, Monday to Friday" and "Lines busy: 5 of 5 · Touches waiting in queue: 18". Tabs below: "Summary" (active, amber underline), "Tasks" with a count badge "12", "Progress". Period chips: "Today" (active, amber), "Week", "Month". A row of four KPI cards: "Calls" 1,284 with "reached 812 — 63%"; "Conversations" 392 with "average 1 min 12 s"; "Hot leads" 38 with "21 with a request"; "Passed to managers" 26 with "leads that got an owner". Below, a large panel "What happened" with a feed of five events, each with a small line icon, bold title, a muted company line, a one-line note and a timestamp on the right, some with rating chips: "Hot lead: asks for a quote" (Great Lakes Freight Co. — Chicago → Dallas, 3 loads a week, chip A); "Manager assigned: Sarah Collins" (Prairie Line Logistics); "Tender window opens in 9 days — reminder created" (Maple Route Carriers); "Follow-up call booked for 10:30 AM CT" (Lone Star Haulers, chip B); "Silent lead moved down to rating D" (Harbor Point Imports). ${UI_STYLE}`,
  },
  {
    name: 'product-contacts',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: Contacts, with "Contacts" highlighted in the sidebar. Page title "Contacts" and subtitle "Lead base: the path of every lead from first touch to a manager." Top right: an outlined "Import" button and a square amber "+" button. A search field "Name, company, phone, email" with a filter icon button. A data table with a header row: checkbox, Name, Company, Phone, Stage, Rating, Manager, Updated ↓. Twelve rows of fictional North American shippers, for example: "Dana Whitfield — Great Lakes Freight Co. — +1 (312) 555-0147 — In progress — A — Sarah Collins — Sep 15, 2026, 4:29 PM"; "Marcus Reid — Lone Star Haulers — +1 (214) 555-0183 — In progress — B — Jordan Price"; "Priya Nair — Maple Route Carriers — +1 (416) 555-0119 — Completed — A — Sarah Collins"; "Tom Becker — Midwest Cold Storage — +1 (614) 555-0110 — In queue — no rating — no manager"; plus Keystone Building Supply, Prairie Line Logistics, Harbor Point Imports, Northstar Grocers, Summit Auto Parts, Cascade Paper Mills, Blue Ridge Beverages, Pacific Coast Produce. Stage pills: "In queue" amber outline, "In progress" neutral, "Completed" green. Rating chips A, B, C, D; missing values shown as a dash. Pagination at the bottom: "25 per page" and "1–25 of 1,742". ${UI_STYLE}`,
  },
  {
    name: 'product-call',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: one call, with "Calls" highlighted in the sidebar. A small "← Back" link. Title "Conversation with Prairie Line Logistics" and a meta line "Sep 15, 2026, 3:49 PM · 2 min 14 s · Prairie Line Logistics". Tags: green "Conversation happened", rating chip "B", "Informativeness 4/5". Top right an outlined button "Contact card". Left, a large panel "Recording and transcript": an audio player with a round amber play button, a thin progress bar "0:00 / 2:14", a "1×" speed button and a download icon; below it a chat-style transcript of alternating bubbles, each with a tiny label "Agent" or "Client" and a timestamp: Agent 0:00 "Hi, this is Emma with MagnaQore Logistic. Do you ship full truckloads out of Kansas City?"; Client 0:06 "We do, mostly dry van to Denver and Salt Lake City."; Agent 0:12 "How many loads a week, and who covers them today?"; Client 0:19 "Around six. Our current carrier keeps missing pickups."; Agent 0:27 "Understood. Can I send a quote and book a call with our manager tomorrow at 10:30?"; Client 0:35 "Sure, send it over." Right column: a panel "What we know about the client" with label–value rows "Number called +1 (816) 555-0132", "Loads per month 24–30", "Contact quality Decision maker", "Lane match Kansas City → Denver", "Stop factors None"; and a panel "Call summary" with short labeled lines "Brief", "Decision maker", "Volume and rates", "Lanes", "Current carrier / pain", "Stop factors", "Interest: high", "Next step: send quote, call Tue 10:30 AM CT". ${UI_STYLE}`,
  },
  {
    name: 'product-contact-card',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: a contact card, with "Contacts" highlighted in the sidebar. A small "← Back" link. Title "Great Lakes Freight Co." with the subtitle "Dana Whitfield · Logistics manager". Tags: "In progress", rating chip "A", "Lead gen · Google Maps". Top right: an outlined button "Stop dialing" and a "…" button. Left column of stacked panels: "What's next" with a task row "The system will call — cascade Rating A, touch 2 — Tomorrow, 9:15 AM CT" and a muted link "Show closed (3)"; "Dialing and calls" with "Cascade Rating A · 3 touches · dialing in progress" and two call rows "Conversation happened · 2 min 41 s — asked for a quote on Chicago → Dallas, 3 loads a week" and "Picked up, no conversation · 18 s", plus a link "All calls (4)"; "Loads" with three compact rows "CHI → DAL · Dry van · 42,000 lb · Covered · Carrier: Northline Transport", "CHI → ATL · Reefer · Booking · Carrier: pending", "MKE → HOU · Flatbed · Quote sent"; "History · 14 events" with a note field "Note about the contact". Right column panels: "Contact details" with rows Phone +1 (312) 555-0147, Email, Position Logistics manager, City Chicago, IL, Segment Food & beverage, Manager "Sarah Collins" shown as a small button, Created Sep 12, 2026, Source card: Google Maps; and "What we know about the client" with rows "Loads per month 12–15", "Contact quality Decision maker", "Lane match Chicago → Dallas", "Stop factors None", "Clarified Sep 15, 2026". ${UI_STYLE}`,
  },
  {
    name: 'product-tasks',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: Dashboard with the "Tasks" tab active (amber underline, badge "12"); the status card is visible above the tabs with "Working hours" and "Lines busy: 4 of 5". Under the tabs a muted line "Tasks across all contacts". A three-column grid of nine task cards; each card has a small line icon, a bold action title, a two-line note written by the AI, a contact and company line, and on some cards a small deadline chip — "Due today" in amber, "Overdue" in muted red, "In 7 days" neutral. Cards: "Contact the client — Tender window opens Sep 24: prepare rates for 40 lanes, submission due Oct 3 — Maple Route Carriers — In 7 days"; "Call the client back — Asked for a call after 2 PM CT with a reefer quote — Lone Star Haulers — Due today"; "Join the chat — Wants a manager to confirm pickup windows — Prairie Line Logistics"; "Call the client back — Agreed on Tuesday 10:30 AM CT, send the updated rate sheet first — Great Lakes Freight Co."; "Contact the client — Q4 dedicated capacity RFP, 12 trucks, due in 10 days — Northstar Grocers"; "Call the client back — Tender documents were not submitted yesterday — Summit Auto Parts — Overdue"; "Contact the client — New lane Toronto → Montreal, 8 loads a month — Cascade Paper Mills"; "Join the chat — Asks for proof of insurance before booking — Blue Ridge Beverages — Due today"; "Call the client back — Decision maker returns Monday — Pacific Coast Produce". Footer "1–9 of 12". ${UI_STYLE}`,
  },
  {
    name: 'product-progress',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: Dashboard with the "Progress" tab active (amber underline). Above the tabs the status card "Working hours · Lines busy: 5 of 5". Under the tabs a dropdown "By segments" and a filter icon button. A vertical list of four wide segment panels. Each panel: segment name on the left and on the right a bold percentage with a muted note like "64% processed 1,152 of 1,800"; a wide horizontal progress bar with an amber fill for processed, a darker amber fill for in progress and a dark track for the rest; under the bar a legend with colored dots "Processed 1,152 · 64%", "In progress 540 · 30%", "Passed to manager 38 · 2%"; and a row "Ratings" with small chips "D 412", "C 388", "B 214", "A 138". Segments: "Food & beverage shippers" (64%), "Building materials" (41%), "Auto parts distributors" (27%), "Retail DCs — Canada" (52%). ${UI_STYLE}`,
  },
  {
    name: 'product-leadgen',
    aspectRatio: '16:9',
    resolution: '4K',
    prompt: `Screen: Lead gen, with "Lead gen" highlighted in the sidebar. Page title "Lead gen" and subtitle "Finding organizations on maps and handing them to contacts". A strip of small pills: "Collected in batch 0", "Handed today 142 of 300", "Spent $6.59", "Per lead $0.007", "Auto-collect at 3:00 AM", "Auto hand-off to contacts" and a muted link "Configure". Top right: an outlined button "Hand to contacts" and an amber button "Collect". Tabs: "Leads" (active), "Summary", "Channels". A search field "Name or phone" with a filter icon. A table with columns Organization, Phone, Rating, Reviews, Stage, What we know, Found ↓, Card. Nine rows; under each organization name a muted line with category and city: "Midwest Cold Storage — Refrigerated warehouse · Columbus, OH — +1 (614) 555-0110 — 4.8 — 150 — Handed to contacts (green pill)"; "Keystone Building Supply — Building materials · Pittsburgh, PA — no phone — 4.9 — 39 — Filtered out (muted pill) with the note Already in base"; "Pacific Coast Produce — Fresh produce distributor · Fresno, CA — 4.9 — 682 — Handed to contacts"; "Northern Timber Co. — Lumber · Thunder Bay, ON — 4.7 — 196 — Filtered out, Chain store"; "Blue Ridge Beverages — Beverage bottler · Roanoke, VA — 5.0 — 255 — Handed to contacts"; plus four more similar rows. The "What we know" column reads "Source card: Google Maps" with the source underlined; the "Found" column shows "Sep 15, 2026, 3:16 AM"; the "Card" column shows a small arrow icon on handed rows. ${UI_STYLE}`,
  },
];
